/*bitmaps generated by lcd assistant software
horizontal little endian
*/
extern rom unsigned char home [];

extern rom const unsigned char benchmark [];
#if 0
extern rom const unsigned char SignalGen [];
#endif
extern rom const unsigned char sine [];
extern rom const unsigned char  square [];
extern rom const unsigned char triangle [];



