
#define DDS_RESET		PORTBbits.RB4
#define DDS_DATA		PORTCbits.RC4
#define DDS_WCLK		PORTCbits.RC3
#define DDS_FQ			PORTCbits.RC7
#define DDS_SQUARE_WAVE PORTCbits.RC5
#define DDS_SINE_WAVE	PORTCbits.RC6

#define HIGH 			1
#define LOW				0

#define	AMPLITUDE_ADDRESS			0X001
#define FREQUENCY_ADDRESS			0X005
#define SIGNAL_TYPE_ADDRESS			0X009
#define SWAP_VALUE_SLOW_FAST		0x00a
#define	ROLL_NO_ADDRESS				0X00A
#define	SERIAL_NO_ADDRESS			0X00B
#define	MODEL_ADDRESS				0X010
#define	BATCH_ADDRESS				0X011
#define	FIRMWARE_ADDRESS			0X017
#define HARDWARE_ADDRESS			0X019

//
#define MAXIMUM_VOLTAGE_LIMIT 19